---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
spec:
  encryptedData: {}
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
    type: Opaque
